# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Pivot_Arm_Gripper_Servo_Joint
      - Pivot_Arm_Gripper_Idol_Joint
    action_ns: follow_joint_trajectory
    default: true